7_Associations/private_events-master/config/routes.rb
PrivateEvents::Application.routes.draw do

  root 'static_pages#home'
  match '/about', to: 'static_pages#about',     via: 'get'

  resources :users, only: [:new, :create, :show, :index]
  match '/signup',  to: 'users#new',            via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :events, only: [:new, :create, :show, :index]

  resources :invites, only: [:create, :destroy]

end

7_Associations/private_events-master/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"

  has_many :invites, :foreign_key => "attended_event_id"
  has_many :attendees, :through => :invites

  scope :upcoming, -> { where("Date >= ?", Date.today).order('Date ASC') }
  scope :past, -> { where("Date < ?", Date.today).order('Date DESC') }

end

7_Associations/private_events-master/app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

7_Associations/private_events-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  require 'pry'
end

7_Associations/private_events-master/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end

  end

  def show
    
    @event = Event.find(params[:id])
    binding.pry
  end

  def index
    # @events = Event.paginate(page: params[:page]).per_page(10)
    @events_upcoming = Event.upcoming.paginate(page: params[:upcoming])
    @events_past = Event.past.paginate(page: params[:past])
    binding.pry
  end

  private
    def event_params
      params.require(:event).permit(:title, :location, :description, :date)
    end

end

7_Associations/private_events-master/app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    @event = Event.find(params[:invite][:attended_event_id])
    current_user.attend!(@event)
    redirect_to @event
  end

  def destroy
    @event = Invite.find(params[:id]).attended_event
    current_user.cancel!(@event)
    redirect_to @event
  end

end

7_Associations/private_events-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user
      sign_in user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

7_Associations/private_events-master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @user = current_user
      @previous_events = @user.previous_events
      @upcoming_events = @user.upcoming_events
    end
  end

  def about
  end
end

7_Associations/private_events-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end    
  end

  def show
    @user = User.find(params[:id])
    @previous_events = @user.previous_events
    @upcoming_events = @user.upcoming_events

  end

  def index
      @users = User.paginate(page: params[:page])
  end

  private

    def user_params
        params.require(:user).permit(:name, :email)
    end

end

7_Associations/private_events-master/app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : nil

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

7_Associations/private_events-master/app/helpers/events_helper.rb
module EventsHelper

  def host?(user)
    current_user == user
  end
end

7_Associations/private_events-master/app/helpers/invites_helper.rb
module InvitesHelper
end

7_Associations/private_events-master/app/helpers/sessions_helper.rb
module SessionsHelper
  require 'pry'
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    #binding.pry
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

   def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  
end

7_Associations/private_events-master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

7_Associations/private_events-master/app/helpers/users_helper.rb
module UsersHelper
end

7_Associations/private_events-master/app/views/events/_attend.html.erb
<%= form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
  <div><%= f.hidden_field :attended_event_id %></div>
  <%= f.submit "Attend", class: "btn btn-large btn-primary" %>
<% end %>

7_Associations/private_events-master/app/views/events/_attend_form.html.erb
<div id="attend_form">
<% if current_user.attending?(@event) %> 
  <%= render 'cancel' %>
<% else %>
  <%= render 'attend' %>
<% end %>
</div>

7_Associations/private_events-master/app/views/events/_cancel.html.erb
<%= form_for(current_user.invites.find_by(attended_event_id: @event.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Cancel", class: "btn btn-large" %>
<% end %>

7_Associations/private_events-master/app/views/events/index.html.erb
<h1>Browse All Events</h1>

<h2>Upcoming</h2>
<%= render 'shared/table', object: @events_upcoming %>
<%= will_paginate @events_upcoming, :param_name => "upcoming" %>

<h2>Past</h2>
<%= render 'shared/table', object: @events_past %>
<%= will_paginate @events_past, :param_name => "past" %>

7_Associations/private_events-master/app/views/events/new.html.erb
<h1>Create Event</h1>

<%= bootstrap_form_for(@event) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :location %>
  <%= f.text_area :description %>
  <%= f.date_field :date%>
  <%= f.submit "Create Event",  class: "btn btn-lg btn-primary"  %>
<% end %>
<br>

7_Associations/private_events-master/app/views/events/show.html.erb
<h1><%= @event.title %></h1>


<% if signed_in? %>
<div class="text-center"><%= render 'attend_form' %></div>
<% end %>

<p><b>Location: </b><%= @event.location %></p> 
<p><b>Host: </b><%= @event.creator.name %></p>

<p><%= @event.description %></p>

</br>

<b>Who's Going:</b>

<ol>
<% @event.attendees.each do |attendee| %>
   <li><%= link_to attendee.name, attendee %></li>

<% end %>
</ol>

7_Associations/private_events-master/app/views/users/index.html.erb
<h1>All Users</h1>

<div class="pagination-wrapper">
<%= will_paginate %>
</div>

<ul class="users">
<% @users.each do |user| %>

  <li><%= link_to user.name, user %></li>

  <% end %>
</ul>

<%= will_paginate %>

7_Associations/private_events-master/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=  bootstrap_form_for @user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :email %>

  <%= f.form_group do %>
      <%= f.submit "Create my account",  class: "btn btn-large btn-primary" %>
  <% end %>

<% end %>

7_Associations/private_events-master/app/views/users/show.html.erb
<h1><%= @user.name %>
<small><%= @user.email %></small></h1>

<% if current_user?(@user) %>
<div class="text-center">
<%= link_to "Create New Event", new_event_path, class: "btn btn-success" %> 
</div>
<% end %>


<% if @upcoming_events.any? %>
<h2>Upcoming</h2>
<%= render 'shared/table', object: @upcoming_events %>
<% end %>

<% if @previous_events.any? %>

<h2>Attended</h2>
<%= render 'shared/table', object: @previous_events %>

<% end %>

<% if @user.events.any? %>
<h2>Created by <%= @user.name%></h2>

<%= render 'shared/table', object: @user.events %>
<% end %>